appearance_encoder_config_path: "configs/model/ae_config.json"
controlnet_config_path: "configs/model/cnet_config.json"

pretrained_model_path: "checkpoints/stable-diffusion-v1-5"
pretrained_vae_path: "checkpoints/sd-vae-ft-mse"
pretrained_controlnet_path: "./checkpoints/ControlNet-v1-1/control_v11p_sd15_openpose_RenamedForMA.pth"
pretrained_appearance_encoder_path: ""
motion_module: "checkpoints/mm_sd_v15_v2.ckpt"

fusion_blocks: "midup"

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  steps_offset: 1
  clip_sample: false

learning_rate: 1e-5
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-8
lr_scheduler: "constant"
max_grad_norm: 1.0

seed:           [1]
steps:          25
guidance_scale: 7.5


source_image:
  - "DATA/TikTok/valid_video/00337/images.mp4"
  - "DATA/TikTok/valid_video/00338/images.mp4"
  - "DATA/TikTok/valid_video/201_002_1x1/images.mp4"
  - "DATA/TikTok/valid_video/201_005_1x1/images.mp4"
  - "DATA/TikTok/valid_video/201_021_1x1/images.mp4"
  - "DATA/TikTok/valid_video/201_024_1x1/images.mp4"
  - "DATA/TikTok/valid_video/202_006_1x1/images.mp4"
  - "DATA/TikTok/valid_video/202_007_1x1/images.mp4"
  - "DATA/TikTok/valid_video/202_025_1x1/images.mp4"
  - "DATA/TikTok/valid_video/203_006_1x1/images.mp4"

video_path:
  - "DATA/TikTok/valid_video/00337/dwpose.mp4"
  - "DATA/TikTok/valid_video/00338/dwpose.mp4"
  - "DATA/TikTok/valid_video/201_002_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/201_005_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/201_021_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/201_024_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/202_006_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/202_007_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/202_025_1x1/dwpose.mp4"
  - "DATA/TikTok/valid_video/203_006_1x1/dwpose.mp4"

size: 512
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false